---
- name: Install powerline fonts
  become: true
  ansible.builtin.apt: 
    name: fonts-powerline
    update_cache: yes

# https://github.com/ryanoasis/nerd-fonts
- name: Download NerdFonts
  become: true
  get_url:
    url: "{{ item }}"
    dest: "{{ ubuntu_font_dir }}"
    mode: "a+r"
  loop: "{{ font_urls }}"
