- hosts: my_machine
  gather_facts: yes

  pre_tasks:
    - debug:
        msg: "Running playbook as user={{ ansible_user_id }}"

  roles:
    - role: common/upgrade
    - role: common/tools
    - role: common/restricted
    - role: development/fonts
    - role: development/shell/zsh
    - role: browsers/chrome
    - role: gnome
    - role: development/ssh
    - role: development/python/system
    - role: development/python/mamba
      mamba_path: ~/mambaforge/
    - role: development/ruby
    - role: development/editors/vscode
    - role: development/editors/neovim
    - role: apps/battery_performance
    - role: apps/media_general
    - role: apps/vlc
    - role: apps/gimp
    - role: apps/spotify
    - role: apps/slack
    - role: apps/eid_belgium
    - role: development/containers/docker
    # - role: drivers/nvidia
    # - role: config

  post_tasks:
    - debug:
        msg: "Reboot to finish"
