---
- name: Add Nvidia repository.
  become: true
  ansible.builtin.apt_repository:
    repo: ppa:graphics-drivers
    state: present 

- name: Install the Nvidia driver.
  become: true
  ansible.builtin.apt: 
    name: "{{ nvidia_driver }}"
    state: latest
    update_cache: yes

- name: Install CUDA
  become: true
  ansible.builtin.apt: 
    name: nvidia-cuda-toolkit
    state: latest
    update_cache: yes
