---
# https://eid.belgium.be/nl/linux-eid-software-installatie
# https://askubuntu.com/questions/1302979/how-do-i-install-the-eid-software-on-ubuntu-20-04
- name: Setup eID-archive
  become: true
  ansible.builtin.apt: 
    deb: "{{ eid_deb_url }}"
    update_cache: yes

- name: Install eID software
  become: true
  ansible.builtin.apt: 
    name: "{{ packages }}"
    state: latest
    update_cache: yes
  vars:
    packages:
    - eid-viewer
    - eid-mw
