---
# Setup dependencies
- name: Enable snap
  become: true
  ansible.builtin.apt:
    name: snapd
    state: latest
    update_cache: yes

# Install Xournal++ via snap
# https://snapcraft.io/install/xournalpp/ubuntu
- name: Install Xournal++
  become: true
  community.general.snap:
    name: xournalpp
