---
- name: Install Ruby
  become: true
  ansible.builtin.apt: 
    name: "{{ packages }}"
    state: latest
    update_cache: yes
  vars:
    packages:
    - ruby-full
    - build-essential
    - zlib1g-dev
