---
# Setup depencencies
- name: Enable snap
  become: true
  apt:
    pkg: snapd
    state: latest
    update_cache: yes

# Install with snap
# https://code.visualstudio.com/docs/setup/linux#_snap
- name: Install VS Code
  become: true
  community.general.snap:
    name: code
    classic: yes
