---
- name: Install tools
  become: true
  ansible.builtin.apt: 
    name: "{{ packages }}"
    state: latest
    update_cache: true
  vars:
    packages:
    - apt-rdepends
    - build-essential
    - curl
    - gpg
    - grep
    - htop
    - jq  # https://stedolan.github.io/jq/
    - less
    - meld  # https://meldmerge.org/development.html
    - openssh-client
    - wget
    - whois

- name: Install compression tools
  become: true
  ansible.builtin.apt: 
    name: "{{ packages }}"
    state: latest
    update_cache: true
  vars:
    packages:
    - gzip
    - tar

- name: Install Git Tools
  become: true
  ansible.builtin.apt: 
    name: "{{ packages }}"
    state: latest
    update_cache: true
  vars:
    packages:
    - git
    - git-cola
    - git-gui
    - gitg
    - gitk

# https://snapcraft.io/docs/installing-snap-on-ubuntu
- name: Enable snap
  become: true
  ansible.builtin.apt:
    pkg: snapd
    state: latest
    update_cache: true
