---
- name: apt update
  become: yes
  apt:
    update_cache: yes
    cache_valid_time: 3600  # One hour

- name: Install tools
  become: yes
  apt: 
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
    - build-essential
    - curl
    - grep
    - htop
    - less
    - openssh-client
    - wget
    - whois

- name: Install compression tools
  become: yes
  apt: 
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
    - gzip
    - tar

- name: Install Git Tools
  become: yes
  apt: 
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
    - git
    - git-cola
    - git-gui
    - gitg
    - gitk

# https://snapcraft.io/docs/installing-snap-on-ubuntu
- name: Enable snap
  become: yes
  apt:
    pkg: snapd
    state: latest
