---
# https://www.spotify.com/us/download/linux/
- name: Setup Spotify repository and install
  block:

  # https://stackoverflow.com/a/72548342/919431
  # https://stackoverflow.com/a/71384057/919431
  - name: Add Spotify GPG key
    become: true
    ansible.builtin.get_url:
      url: "{{ spotify_sign_key }}"
      dest: "{{ spotify_key_file_local }}"
      mode: '0644'
      force: true

  - name: De-Armor Spotify GPG key
    command:  "gpg --dearmor <{{ spotify_key_file_local }} > {{ spotify_key_file_local }}"
    args:
      creates: "{{ spotify_key_file_local }}"

  - name: Add Spotify repo
    become: true
    ansible.builtin.apt_repository:
      repo: "deb [arch=amd64 signed-by={{ spotify_key_file_local }}] {{ spotify_repo_url }} stable non-free"
      filename: spotify
      state: present

  - name: Install Spotify
    become: true
    ansible.builtin.apt: 
      name: spotify-client
      state: latest
      update_cache: yes

  - shell: "spotify --version"
    register: spotify_version
  - debug:
      msg: "Spotify version is {{ spotify_version.stdout }}"
